### ISSUE TITLE
Menu entry does not show

### ISSUE THREAD

**Issue by asheiduk** [certainlyakey/Copy-current-page-URL-with-anchor#5] opened 2021-06-04 09:03 UTC
There is no menu entry in the right click menu. 

Firefox 89.0 on Ubuntu 18.04 LTS.

example page: https://en.wikipedia.org/wiki/Wikipedia

**Comment by kernc** [comment] 2021-06-04 11:16
Duplicate of https://github.com/certainlyakey/Copy-current-page-URL-with-anchor/issues/4.

**Comment by certainlyakey** [comment] 2023-05-06 17:29
Closing as a duplicate.

**Closed as completed by certainlyakey** 2023-05-06 17:29 UTC
